name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Build iframe
        run: |
          echo '<iframe width="100%" height="100%" frameborder="0" src="https://${{ github.event.repository.name }}.pages.dev"></iframe>' > index.html

      - name: Deploy to GitHub Pages
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: .
